# 基础镜像
FROM redis
# author
MAINTAINER fxy

# 挂载目录
VOLUME /home/fxy/redis
# 创建目录
RUN mkdir -p /home/fxy/redis
# 指定路径
WORKDIR /home/fxy/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/fxy/redis/redis.conf
