# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER fxy

# 挂载目录
VOLUME /home/fxy
# 创建目录
RUN mkdir -p /home/fxy
# 指定路径
WORKDIR /home/fxy
# 复制jar文件到路径
COPY ./jar/fxy-modules-job.jar /home/fxy/fxy-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","fxy-modules-job.jar"]