# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER fxy

# 挂载目录
VOLUME /home/fxy
# 创建目录
RUN mkdir -p /home/fxy
# 指定路径
WORKDIR /home/fxy
# 复制jar文件到路径
COPY ./jar/fxy-visual-monitor.jar /home/fxy/fxy-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","fxy-visual-monitor.jar"]